export const webProjects = [
  {
    id: 1,
    image: "/images/brainstack/LogoBrainStack.svg",
    title: "Brain Stack",
    role: "Frontend Developer, Neue Fische 2024",
    tools: [
      "React",
      "Next.js",
      "OpenAI",
      "MongoDB",
      "SWR",
      "NextAuth",
      "Framer Motion",
      "Cloudinary",
    ],
    text: "BRAIN STACK is a straightforward and accessible flashcard learning application. Users have the option of either creating their own flashcard collections or employing artificial intelligence to generate them. The application provides three learning modes that are designed to make learning enjoyable and effective. This group project was initiated during the concluding phase of the neue fische web development bootcamp.",
    link: "https://capstone-flip-wise.vercel.app/",
    repository: "https://github.com/eneben/capstone-flip-wise/",
    highlight: true,
  },
  {
    id: 2,
    image: "/images/tourioApp/tourio.jpg",
    title: "Tourio App, Practice task",
    role: "Frontend Developer, Neue Fische 2024",
    tools: ["React", "Next.js", "SWR"],
    text: "A small application that allows you to create and save a personal collection of places of interest. This project was created during the neue fische web development bootcamp.",
    link: "https://tourio-app-nu.vercel.app/",
    repository: "https://github.com/IsabellUrban/tourio-app",
    highlight: false,
  },
  {
    id: 3,
    image: "/images/artgalleryApp/orange.jpg",
    title: "Art Gallery App, Practice task",
    role: "Frontend Developer, Neue Fische 2024",
    tools: ["React", "Next.js", "SWR"],
    text: "An art gallery app that displays a list of artworks with a spotlight, gallery and detail page. API integration with bookmark functionality.",
    link: "https://art-gallery-app-two.vercel.app/",
    repository: "https://github.com/IsabellUrban/art-gallery-app/tree/main",
    highlight: false,
  },
  {
    id: 4,
    image: "/images/themeCreator/theme.jpg",
    title: "Theme Creator, Practice task",
    role: "Frontend Developer, Neue Fische 2024",
    tools: ["React", "CSS", "JavaScript"],
    text: "This app lets you make, edit and delete colour themes. This project was created during the neue fische web development bootcamp.",
    link: "https://theme-creator-eight.vercel.app/",
    repository: "https://github.com/IsabellUrban/theme-creator",
    highlight: false,
  },
  {
    id: 5,
    image: "/images/quizApp/quiz.jpg",
    title: "HP Quiz App, Practice task",
    role: "Frontend Developer, Neue Fische 2024",
    tools: ["HTML", "CSS", "JavaScript"],
    text: "This is the first app I built to help me learn how to use HTML, CSS and JavaScript. It's a simple quiz app about Harry Potter.",
    link: "https://quiz-app-three-murex.vercel.app/",
    repository: "https://github.com/IsabellUrban/quiz-app",
    highlight: false,
  },
];