export const projects = [
  {
    id: 1,
    title: "Kieselbach Berlin ",
    preview: {
      src: "/images/kieselbach/GreyBlending.mp4",
      type: "video",
    },
    description:
      "I designed an e-book for Anja Kieselbach for Grey Blending. In addition to the e-book, I created social media posts.",
    agency: "Urban Design",
    media: [
      {
        id: 1,
        type: "image",
        src: "/images/kieselbach/e-book-01.jpg",
        alt: "Grey Blending e-book",
        layout: "large desktop-large",
      },
      {
        id: 2,
        type: "image",
        src: "/images/kieselbach/e-book-02.jpg",
        alt: "Grey Blending e-book",
        layout: "large desktop-large",
      },
      {
        id: 3,
        type: "image",
        src: "/images/kieselbach/e-book-03.jpg",
        alt: "Grey Blending e-book",
        layout: "large desktop-large",
      },
      {
        id: 4,
        type: "image",
        src: "/images/kieselbach/e-book-04.jpg",
        alt: "Grey Blending e-book",
        layout: "large desktop-large",
      },
      {
        id: 5,
        type: "video",
        src: "/images/kieselbach/GreyBlending.mp4",
        alt: "Grey Blending Instgram Reel",
        layout: "large desktop-large",
      },
    ],
  },
  {
    id: 2,
    title: "Bild Shop",
    preview: {
      src: "/images/bildshop/bildshop_01.jpg",
      type: "image",
    },
    description:
      "Created web designs for BILD Shop, including campaigns for newsletters and banners. Edited product photos and descriptions and designed teasers, banners and mockups to maintain a polished online presence.",
    agency: "Axelspringer SE",
    media: [
      {
        id: 1,
        type: "image",
        src: "/images/bildshop/bildshop_01.jpg",
        alt: "Picture of the BILD Shop Website",
        layout: "large desktop-large",
      },
      {
        id: 2,
        type: "image",
        src: "/images/bildshop/bildshop_03.jpg",
        alt: "Picture of the BILD Shop Website",
        layout: "wide desktop-wide",
      },
      {
        id: 3,
        type: "image",
        src: "/images/bildshop/bildshop_07.jpg",
        alt: "Picture of the BILD Shop Website",
        layout: "",
      },
      {
        id: 4,
        type: "image",
        src: "/images/bildshop/bildshop_04_tall.jpg",
        alt: "Picture of the BILD Shop Website",
        layout: "tall desktop-tall",
      },
      {
        id: 5,
        type: "image",
        src: "/images/bildshop/bildshop_08.jpg",
        alt: "Picture of the BILD Shop Website",
        layout: "",
      },
      {
        id: 6,
        type: "image",
        src: "/images/bildshop/bildshop_05_large.jpg",
        alt: "Picture of the BILD Shop Website",
        layout: "large desktop-large",
      },
      {
        id: 7,
        type: "image",
        src: "/images/bildshop/bildshop_06.jpg",
        alt: "Picture of the BILD Shop Website",
        layout: "",
      },
      {
        id: 8,
        type: "image",
        src: "/images/bildshop/bildshop_09_large.jpg",
        alt: "Picture of the BILD Shop Website",
        layout: "large desktop-large",
      },
    ],
  },
  {
    id: 3,
    title: "SAP Blaupause",
    preview: {
      src: "/images/blaupause/blaupause_01.jpg",
      type: "image",
    },
    description:
      "I designed these pages according to the brand guidelines for the customer magazine SAP Blaupause.",
    agency: "Agentur dieleutefürkommunikation",
    media: [
      {
        id: 1,
        type: "image",
        src: "/images/blaupause/blaupause_04_tall.jpg",
        alt: "Picture of the SAP Blaupause Site",
        layout: "tall desktop-tall",
      },
      {
        id: 2,
        type: "image",
        src: "/images/blaupause/blaupause_03_large.jpg",
        alt: "Picture of the SAP Blaupause Site",
        layout: "desktop-wide",
      },
      {
        id: 3,
        type: "image",
        src: "/images/blaupause/blaupause_05.jpg",
        alt: "Picture of the SAP Blaupause Site",
        layout: "",
      },
      {
        id: 4,
        type: "image",
        src: "/images/blaupause/blaupause_02.jpg",
        alt: "blaupause_03",
        layout: "large desktop-large",
      },
    ],
  },
  {
    id: 4,
    title: "Tipi Tapa",
    preview: {
      src: "/images/tipitapa/tipitapa_logo_website.jpg",
      type: "image",
    },
    description:
      "Tipi Tapa offers play and movement groups for children. I was asked to develop a new, modern branding. This included designing the logo, flyer, business stationery and website.",
    agency: "Urban Design",
    media: [
      {
        id: 1,
        type: "image",
        src: "/images/tipitapa/tipitapa_logo_website.jpg",
        alt: "Picture of the Tipi Tapa Website",
        layout: "large desktop-large",
      },
      {
        id: 2,
        type: "image",
        src: "/images/tipitapa/tipitapa_logo_01.jpg",
        alt: "Picture of the Tipi Tapa Logo",
        layout: "desktop-large",
      },
      {
        id: 3,
        type: "image",
        src: "/images/tipitapa/tipitapa_logo_02.jpg",
        alt: "Picture of the Tipi Tapa Logo",
        layout: "desktop-large",
      },
      {
        id: 4,
        type: "image",
        src: "/images/tipitapa/tipitapa_large.jpg",
        alt: "Picture of the Tipi Tapa Flyer",
        layout: "large desktop-large",
      },
    ],
  },
  {
    id: 5,
    title: "Vancouver Westside German School",
    preview: {
      src: "/images/vwgs/vwgs_foto_flyer.jpg",
      type: "image",
    },
    description:
      "For the Vancouver Westside German School  I did the design of a new flyer and a strategic plan.",
    agency: "Urban Design",
    media: [
      {
        id: 1,
        type: "image",
        src: "/images/vwgs/vwgs_flyer.jpg",
        alt: "Picture of the Vancouver Westside German School Flyer",
        layout: "large desktop-large",
      },
      {
        id: 2,
        type: "image",
        src: "/images/vwgs/vwgs_foto_flyer.jpg",
        alt: "Picture of the Vancouver Westside German School Flyer",
        layout: "wide desktop-wide",
      },
      {
        id: 3,
        type: "image",
        src: "/images/vwgs/vwgs_strategicplan_large.jpg",
        alt: "Picture of the Vancouver Westside German School Strategic Plan",
        layout: "large desktop-large",
      },
    ],
  },
  {
    id: 6,
    title: "Wilding Bliss",
    preview: {
      src: "/images/wildingbliss/wb_collage.jpg",
      type: "image",
    },
    description:
      "I designed a logo and business cards for a small company that makes wellness shower steamers. I also made a stamp for the packaging design.",
    agency: "Urban Design",
    media: [
      {
        id: 1,
        type: "image",
        src: "/images/wildingbliss/wb_stamp_large.jpg",
        alt: "Picture of the Wilding Bliss Stamp",
        layout: "large desktop-large",
      },
      {
        id: 2,
        type: "image",
        src: "/images/wildingbliss/wb_businesscard.jpg",
        alt: "Picture of the Wilding Bliss Business Card",
        layout: "large desktop-large",
      },
      {
        id: 3,
        type: "image",
        src: "/images/wildingbliss/wb_package_normal.jpg",
        alt: "Picture of the Wilding Bliss Packaging Design",
        layout: "wide dektop-wide",
      },
      {
        id: 4,
        type: "image",
        src: "/images/wildingbliss/wb_logo.jpg",
        alt: "Picture of the Wilding Bliss Logo",
        layout: "wide desktop-wide",
      },
    ],
  },
  {
    id: 7,
    title: "Shoppinguide 360° Magazine",
    preview: {
      src: "/images/360/360_titel.jpg",
      type: "image",
    },
    description:
      "A shopping guide for Berlin with the highlight of 360 degree photos. It is divided into districts and contains different categories. We developed the general design and I designed the layout and the different categories of the magazine. The magazine was produced several times a year.",
    agency: "In Touch Agentur",
    media: [
      {
        id: 1,
        type: "image",
        src: "/images/360/360_titel.jpg",
        alt: "Picture of the Shoppinguide 360° Magazine",
        layout: "large desktop-large",
      },
      {
        id: 2,
        type: "image",
        src: "/images/360/360_01.jpg",
        alt: "Picture of the Shoppinguide 360° Magazine",
        layout: "large desktop-large",
      },
      {
        id: 3,
        type: "image",
        src: "/images/360/360_02.jpg",
        alt: "Picture of the Shoppinguide 360° Magazine",
        layout: "large desktop-large",
      },
      {
        id: 4,
        type: "image",
        src: "/images/360/360_03.jpg",
        alt: "Picture of the Shoppinguide 360° Magazine",
        layout: "large desktop-large",
      },
    ],
  },
  {
    id: 8,
    title: "Volunteering New Zealand",
    preview: {
      src: "/images/vnz/vnz_report_title.jpg",
      type: "image",
    },
    description:
      "My work for Volunteering New Zealand has included designing their annual report from concept to finished print. I also designed a logo for a conference and the associated promotional material. I created information brochures and web banners.",
    agency: "Urban Design",
    media: [
      {
        id: 1,
        type: "image",
        src: "/images/vnz/vnz_report_title.jpg",
        alt: "Picture of the VNZ Annual Report",
        layout: "large desktop-large",
      },
      {
        id: 2,
        type: "image",
        src: "/images/vnz/vnz_report_01.jpg",
        alt: "Picture of the VNZ Annual Report",
        layout: "wide desktop-wide",
      },
      {
        id: 3,
        type: "image",
        src: "/images/vnz/vnz_pivot.jpg",
        alt: "Picture of the Pivot Conference Logo",
        layout: "",
      },
      {
        id: 4,
        type: "image",
        src: "/images/vnz/vnz_banner_tall.jpg",
        alt: "Picture of different VNZ Web Banners",
        layout: "tall desktop-tall",
      },
      {
        id: 5,
        type: "image",
        src: "/images/vnz/vnz_etu.jpg",
        alt: "Picture of the etu Conference Logo",
        layout: "",
      },
      {
        id: 6,
        type: "image",
        src: "/images/vnz/vnz_nudging_large.jpg",
        alt: "Picture of the nudging workshop poster",
        layout: "large desktop-large",
      },
      {
        id: 7,
        type: "image",
        src: "/images/vnz/vnz_sdg_large.jpg",
        alt: "Picture of the SDG poster",
        layout: "",
      },
    ],
  },
  {
    id: 9,
    title: "2020 Communication Trust",
    preview: {
      src: "/images/2020Trust/2020Trust_03.jpg",
      type: "image",
    },
    description:
      "2020 Trust is an organisation based in New Zealand that is dedicated to the promotion of digital inclusion on a cross-sectoral basis. I was commissioned to design its annual report. ",
    agency: "Urban Design",
    media: [
      {
        id: 1,
        type: "image",
        src: "/images/2020Trust/2020Trust_01_large.jpg",
        alt: "Picture of the 2020 Trust Annual Report",
        layout: "large desktop-large",
      },
      {
        id: 2,
        type: "image",
        src: "/images/2020Trust/2020Trust_02_large.jpg",
        alt: "Picture of the 2020 Trust Annual Report",
        layout: "large desktop-large",
      },
    ],
  },
];
